# Generated by Django 5.2.1 on 2025-05-20 14:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gisapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exitborder",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
