# Generated by Django 5.2.1 on 2025-05-20 14:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gisapp", "0002_exitborder_geom"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValuesPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objectid", models.IntegerField(unique=True)),
                ("values", models.FloatField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ExitBorder",
        ),
    ]
