# Generated by Django 5.2.1 on 2025-05-20 20:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gisapp", "0003_valuespoints_delete_exitborder"),
    ]

    operations = [
        migrations.RenameField(
            model_name="valuespoints",
            old_name="values",
            new_name="f2",
        ),
        migrations.RemoveField(
            model_name="valuespoints",
            name="objectid",
        ),
        migrations.AddField(
            model_name="valuespoints",
            name="date",
            field=models.FloatField(default="010101", max_length=6),
        ),
        migrations.AddField(
            model_name="valuespoints",
            name="e_w_indica",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="valuespoints",
            name="f12",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="valuespoints",
            name="f3",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="valuespoints",
            name="ground_spe",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="valuespoints",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="valuespoints",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="valuespoints",
            name="n_s_indica",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="valuespoints",
            name="position",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="valuespoints",
            name="state",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="valuespoints",
            name="utc_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="valuespoints",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
