# Generated by Django 5.2.1 on 2025-05-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gisapp", "0004_rename_values_valuespoints_f2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="valuespoints",
            name="date",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
