# Generated by Django 4.2 on 2025-06-17 01:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisapp', '0005_alter_valuespoints_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSMLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField()),
                ('tags', models.JSONField(default=dict)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=3857)),
            ],
            options={
                'db_table': 'planet_osm_line',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OSMPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField()),
                ('tags', models.JSONField(default=dict)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=3857)),
            ],
            options={
                'db_table': 'planet_osm_point',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OSMPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField()),
                ('tags', models.JSONField(default=dict)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=3857)),
            ],
            options={
                'db_table': 'planet_osm_polygon',
                'managed': False,
            },
        ),
    ]
